# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./LLM_KC_SN_InvoicingSystem_OOD4/LLM_KC_SN_InvoicingSystem_OOD4.sln
    - name: Build
      run: dotnet build ./LLM_KC_SN_InvoicingSystem_OOD4/LLM_KC_SN_InvoicingSystem_OOD4.sln --no-restore
    - name: Test
      run: dotnet test ./LLM_KC_SN_InvoicingSystem_OOD4/LLM_KC_SN_InvoicingSystem_OOD4.sln --no-build --verbosity normal
